<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ISILLT10137" ignored="0" name="Desktop1" tests="1" failures="1" timestamp="23 Jul 2018 09:51:47 GMT" time="3.275" errors="0">
  <testcase name="TC001" time="3.212" classname="testCases.TestCases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at scenarios.CustomSignInTest.customSignInTestScenario(CustomSignInTest.java:35)
	at testCases.TestCases.TC001(TestCases.java:131)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TC001 -->
</testsuite> <!-- Desktop1 -->
